// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BillingComponent: typeof import('./src/components/BillingComponent.vue')['default']
    DependenciesComponent: typeof import('./src/components/DependenciesComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ExampleComponent: typeof import('./src/components/dialogs/ExampleComponent.vue')['default']
    LoginDialog: typeof import('./src/components/dialogs/LoginDialog.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    WindowFrame: typeof import('./src/components/WindowFrame.vue')['default']
  }
}
