// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BillingComponent: typeof import('./src/components/BillingComponent.vue')['default']
    DrawerContainer: typeof import('./src/components/drawers/DrawerContainer.vue')['default']
    DrawerLaporanBilling: typeof import('./src/components/drawers/DrawerLaporanBilling.vue')['default']
    DrawerPengaturanAdmin: typeof import('./src/components/drawers/DrawerPengaturanAdmin.vue')['default']
    DrawerPengaturanAplikasi: typeof import('./src/components/drawers/DrawerPengaturanAplikasi.vue')['default']
    DrawerPengaturanKonsumsi: typeof import('./src/components/drawers/DrawerPengaturanKonsumsi.vue')['default']
    DrawerPengaturanSewa: typeof import('./src/components/drawers/DrawerPengaturanSewa.vue')['default']
    DrawerPengeluaran: typeof import('./src/components/drawers/DrawerPengeluaran.vue')['default']
    DrawerSewa: typeof import('./src/components/drawers/DrawerSewa.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    LoginDialog: typeof import('./src/components/dialogs/LoginDialog.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MejaMain: typeof import('./src/components/MejaMain.vue')['default']
    PengaturanAdmin: typeof import('./src/components/PengaturanAdmin.vue')['default']
    PengaturanAplikasi: typeof import('./src/components/PengaturanAplikasi.vue')['default']
    PengaturanKonsumsi: typeof import('./src/components/PengaturanKonsumsi.vue')['default']
    PengaturanSewa: typeof import('./src/components/PengaturanSewa.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    WindowFrame: typeof import('./src/components/WindowFrame.vue')['default']
  }
}
